server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carbon_policy_db
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.carbon.entity
  configuration:
    map-underscore-to-camel-case: true
wdm:
  # 使用清华大学的镜像源，下载速度飞快
  mirror: https://npmmirror.com/mirrors/chromedriver